import type { Listing, AnalysisResult } from "../types";

export const MOCK_LISTINGS: Listing[] = [
  {
    listing_id: "1001",
    url: "https://www.facebook.com/marketplace/item/1001",
    title: "2019 Toyota Camry SE — One Owner, Clean Title",
    price: 18500,
    year: 2019,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    mileage: 54200,
    location: "Austin, TX",
    seller_name: "Marcus T.",
    seller_type: "private",
    posted_at: null,
    images: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
    ],
    description:
      "One owner, no accidents. Bought new in 2019. Regular oil changes at Toyota dealership. New tires in 2023. VIN: 4T1B11HK9KU213456",
    vin: "4T1B11HK9KU213456",
    decoded_vin: {
      vin: "4T1B11HK9KU213456",
      make: "Toyota",
      model: "Camry",
      year: 2019,
      trim: "SE",
      engine: "2.5L I4",
      transmission: "Automatic",
      drive_type: "FWD",
      body_style: "Sedan",
      plant_country: "USA",
    },
    history: {
      vin: "4T1B11HK9KU213456",
      recalls: [],
      open_recall_count: 0,
      complaints: [],
      complaint_count: 1,
      recall_count: 0,
      nicb_stolen: false,
      nicb_salvage: false,
      fetched_at: new Date().toISOString(),
    },
    quick_score: 84,
    market_price_estimate: 19200,
    price_delta_pct: -3.6,
    title_check_url: "https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle",
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?vin=4T1B11HK9KU213456",
    autocheck_url: "https://www.autocheck.com/vehiclehistory/autocheck/en/vehiclehistory?vin=4T1B11HK9KU213456",
    scraped_at: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    listing_id: "1002",
    url: "https://www.facebook.com/marketplace/item/1002",
    title: "2017 Honda Civic EX — Low Miles, Backup Camera",
    price: 14900,
    year: 2017,
    make: "Honda",
    model: "Civic",
    trim: "EX",
    mileage: 61800,
    location: "Denver, CO",
    seller_name: "Denver Auto Outlet",
    seller_type: "dealer",
    posted_at: null,
    images: [
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80",
    ],
    description:
      "2017 Honda Civic EX. Clean history. Backup camera, Apple CarPlay, heated front seats. VIN: 2HGFC2F72HH512345",
    vin: "2HGFC2F72HH512345",
    decoded_vin: {
      vin: "2HGFC2F72HH512345",
      make: "Honda",
      model: "Civic",
      year: 2017,
      trim: "EX",
      engine: "1.5L I4 Turbo",
      transmission: "CVT",
      drive_type: "FWD",
      body_style: "Sedan",
      plant_country: "USA",
    },
    history: {
      vin: "2HGFC2F72HH512345",
      recalls: [
        {
          recall_id: "17V123000",
          component: "Air Bags",
          summary: "Takata airbag inflator may rupture in a crash.",
          consequence: "Inflator could rupture with metal fragmentation, causing injury or death.",
          remedy: "Replace airbag inflator free of charge at any Honda dealer.",
          date: "2017-03-15",
        },
      ],
      open_recall_count: 0,
      complaints: [],
      complaint_count: 2,
      recall_count: 1,
      nicb_stolen: false,
      nicb_salvage: false,
      fetched_at: new Date().toISOString(),
    },
    quick_score: 67,
    market_price_estimate: 15400,
    price_delta_pct: -3.2,
    title_check_url: "https://mydmv.colorado.gov/",
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?vin=2HGFC2F72HH512345",
    autocheck_url: "https://www.autocheck.com/vehiclehistory/autocheck/en/vehiclehistory?vin=2HGFC2F72HH512345",
    scraped_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    listing_id: "1003",
    url: "https://www.facebook.com/marketplace/item/1003",
    title: "2015 Ford F-150 XLT — 4x4, Tow Package",
    price: 22900,
    year: 2015,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    mileage: 98700,
    location: "Phoenix, AZ",
    seller_name: "Kevin R.",
    seller_type: "private",
    posted_at: null,
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
    ],
    description:
      "2015 Ford F-150 XLT SuperCrew 4x4. 5.0L V8. Tow package, spray-in bedliner. VIN: 1FTEW1EF5FFB67890",
    vin: "1FTEW1EF5FFB67890",
    decoded_vin: {
      vin: "1FTEW1EF5FFB67890",
      make: "Ford",
      model: "F-150",
      year: 2015,
      trim: "XLT",
      engine: "5.0L V8",
      transmission: "Automatic",
      drive_type: "4WD",
      body_style: "Pickup",
      plant_country: "USA",
    },
    history: {
      vin: "1FTEW1EF5FFB67890",
      recalls: [
        {
          recall_id: "15V394000",
          component: "Power Train: Automatic Transmission",
          summary: "Transmission may downshift unexpectedly.",
          consequence: "Unexpected downshift increases crash risk.",
          remedy: "Software update at dealership at no charge.",
          date: "2015-07-01",
        },
      ],
      open_recall_count: 0,
      complaints: [],
      complaint_count: 5,
      recall_count: 1,
      nicb_stolen: false,
      nicb_salvage: false,
      fetched_at: new Date().toISOString(),
    },
    quick_score: 58,
    market_price_estimate: 21500,
    price_delta_pct: 6.5,
    title_check_url: "https://azmvdnow.gov/home",
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?vin=1FTEW1EF5FFB67890",
    autocheck_url: "https://www.autocheck.com/vehiclehistory/autocheck/en/vehiclehistory?vin=1FTEW1EF5FFB67890",
    scraped_at: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    listing_id: "1004",
    url: "https://www.facebook.com/marketplace/item/1004",
    title: "2021 Subaru Outback Premium — AWD, EyeSight, 1 Owner",
    price: 26800,
    year: 2021,
    make: "Subaru",
    model: "Outback",
    trim: "Premium",
    mileage: 31500,
    location: "Seattle, WA",
    seller_name: "Priya M.",
    seller_type: "private",
    posted_at: null,
    images: [
      "https://images.unsplash.com/photo-1551830820-330a71b99659?w=800&q=80",
    ],
    description:
      "2021 Subaru Outback Premium AWD. EyeSight, adaptive cruise, blind spot. 31k miles, dealer serviced. VIN: 4S4BTAFC3M3123456",
    vin: "4S4BTAFC3M3123456",
    decoded_vin: {
      vin: "4S4BTAFC3M3123456",
      make: "Subaru",
      model: "Outback",
      year: 2021,
      trim: "Premium",
      engine: "2.5L H4",
      transmission: "CVT",
      drive_type: "AWD",
      body_style: "Wagon",
      plant_country: "USA",
    },
    history: {
      vin: "4S4BTAFC3M3123456",
      recalls: [],
      open_recall_count: 0,
      complaints: [],
      complaint_count: 0,
      recall_count: 0,
      nicb_stolen: false,
      nicb_salvage: false,
      fetched_at: new Date().toISOString(),
    },
    quick_score: 91,
    market_price_estimate: 28200,
    price_delta_pct: -5.0,
    title_check_url: "https://www.dol.wa.gov/vehicleregistration/",
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?vin=4S4BTAFC3M3123456",
    autocheck_url: "https://www.autocheck.com/vehiclehistory/autocheck/en/vehiclehistory?vin=4S4BTAFC3M3123456",
    scraped_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    listing_id: "1005",
    url: "https://www.facebook.com/marketplace/item/1005",
    title: "2016 BMW 328i Sport Line — Nav, Sunroof, Needs Work",
    price: 11200,
    year: 2016,
    make: "BMW",
    model: "328i",
    trim: "Sport Line",
    mileage: 112300,
    location: "Chicago, IL",
    seller_name: "Lakeview Motors",
    seller_type: "dealer",
    posted_at: null,
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    ],
    description:
      "2016 BMW 328i Sport Line. Navigation, sunroof, heated seats. Needs front control arm bushings. VIN: WBA8E9C51GK123789",
    vin: "WBA8E9C51GK123789",
    decoded_vin: {
      vin: "WBA8E9C51GK123789",
      make: "BMW",
      model: "328i",
      year: 2016,
      trim: "Sport Line",
      engine: "2.0L I4 Turbo",
      transmission: "Automatic",
      drive_type: "RWD",
      body_style: "Sedan",
      plant_country: "Germany",
    },
    history: {
      vin: "WBA8E9C51GK123789",
      recalls: [
        {
          recall_id: "16V394000",
          component: "Fuel System",
          summary: "Fuel pump may fail causing engine stall.",
          consequence: "Engine stall increases crash risk.",
          remedy: "Replace fuel pump at no charge.",
          date: "2016-06-20",
        },
      ],
      open_recall_count: 1,
      complaints: [],
      complaint_count: 11,
      recall_count: 1,
      nicb_stolen: false,
      nicb_salvage: false,
      fetched_at: new Date().toISOString(),
    },
    quick_score: 32,
    market_price_estimate: 13500,
    price_delta_pct: -17.0,
    title_check_url: "https://www.ilsos.gov/facilitieslocator/",
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?vin=WBA8E9C51GK123789",
    autocheck_url: "https://www.autocheck.com/vehiclehistory/autocheck/en/vehiclehistory?vin=WBA8E9C51GK123789",
    scraped_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    listing_id: "1006",
    url: "https://www.facebook.com/marketplace/item/1006",
    title: "2020 Mazda CX-5 Touring — AWD, Bose Audio, Low Miles",
    price: 24500,
    year: 2020,
    make: "Mazda",
    model: "CX-5",
    trim: "Touring",
    mileage: 38900,
    location: "Nashville, TN",
    seller_name: "Alicia W.",
    seller_type: "private",
    posted_at: null,
    images: [
      "https://images.unsplash.com/photo-1616788494707-ec28f08d05a1?w=800&q=80",
    ],
    description:
      "2020 Mazda CX-5 Touring AWD. Bose audio, power liftgate, heated seats, blind spot. 39k miles, dealer serviced. VIN: JM3KFBCM9L0123456",
    vin: "JM3KFBCM9L0123456",
    decoded_vin: {
      vin: "JM3KFBCM9L0123456",
      make: "Mazda",
      model: "CX-5",
      year: 2020,
      trim: "Touring",
      engine: "2.5L I4",
      transmission: "Automatic",
      drive_type: "AWD",
      body_style: "SUV",
      plant_country: "Japan",
    },
    history: {
      vin: "JM3KFBCM9L0123456",
      recalls: [],
      open_recall_count: 0,
      complaints: [],
      complaint_count: 0,
      recall_count: 0,
      nicb_stolen: false,
      nicb_salvage: false,
      fetched_at: new Date().toISOString(),
    },
    quick_score: 88,
    market_price_estimate: 25800,
    price_delta_pct: -5.0,
    title_check_url: "https://www.tn.gov/revenue/vehicle-title-and-registration.html",
    carfax_url: "https://www.carfax.com/VehicleHistory/p/Report.cfx?vin=JM3KFBCM9L0123456",
    autocheck_url: "https://www.autocheck.com/vehiclehistory/autocheck/en/vehiclehistory?vin=JM3KFBCM9L0123456",
    scraped_at: new Date(Date.now() - 3 * 60000).toISOString(),
  },
];

export const MOCK_ANALYSES: Record<string, AnalysisResult> = {
  "4T1B11HK9KU213456": {
    listing_id: "1001",
    buy_rating: "BUY",
    buy_score: 8,
    reliability_summary:
      "The 2019 Toyota Camry SE with the 2.5L 4-cylinder is one of the most dependable mid-size sedans on the market. Toyota's reputation for longevity is well-earned here — this generation regularly sees 200k+ miles with basic maintenance. No major powertrain issues are reported at this mileage range.",
    known_pain_points: [
      "Some owners report wind noise from the A-pillar at highway speeds — check door seals",
      "Infotainment system can be slow to respond in cold weather",
      "Minor oil consumption (under 1qt/5k miles) is within Toyota spec",
    ],
    recall_warnings: [],
    maintenance_at_mileage: [
      "Transmission fluid change recommended at 60k miles — ask for service records",
      "Spark plugs due at 60k miles (iridium, $120–$180)",
      "Brake fluid flush due (every 3 years regardless of mileage)",
      "Inspect coolant condition — replace at 100k miles",
    ],
    inspection_checklist: [
      "Check all 4 tires for even wear",
      "Inspect undercarriage for rust",
      "Test all HVAC functions including rear defroster",
      "Verify backup camera image is clear",
      "Check for any oil leaks at valve cover gasket",
      "Test all power windows and locks",
    ],
    seller_questions: [
      "Do you have service records? Specifically oil changes and the 60k service?",
      "Has the car been in any accidents, even minor ones not on Carfax?",
      "Why are you selling?",
      "Are there any warning lights on or recent repairs done?",
    ],
    buy_rationale:
      "At $18,500 — $700 below market — this is solid value for a clean, single-owner 2019 Camry with only 54k miles. No recalls, minimal complaints, and the mileage is low enough that the major services are just coming due, not overdue. Recommend a pre-purchase inspection to confirm suspension and brakes.",
    price_assessment: "underpriced",
    ownership_cost: {
      annual_maintenance_estimate: 750,
      common_repair_costs: [
        "Brake pads + rotors: $350–$550",
        "Tires (set of 4): $500–$700",
        "Transmission fluid service: $180–$250",
      ],
      insurance_tier: "low",
      fuel_cost_annual_estimate: 1600,
    },
    negotiation_script:
      "Hi Marcus, I've done some research on this Camry and I'm genuinely interested. The 60k service interval is coming up — transmission fluid, spark plugs, brake flush — about $400–$500 at a shop. Would you consider $17,800? I'm a serious buyer, can meet at a mechanic this week, and can pay same day if everything checks out.",
  },
  JM3KFBCM9L0123456: {
    listing_id: "1006",
    buy_rating: "BUY",
    buy_score: 9,
    reliability_summary:
      "The 2020 Mazda CX-5 Touring is widely regarded as the benchmark compact SUV for reliability and driving dynamics. The 2.5L Skyactiv-G engine is proven and robust. Dealer-serviced with 39k miles means this vehicle is well within its prime years with no significant wear expected.",
    known_pain_points: [
      "Infotainment commander knob has a learning curve",
      "Rear cargo area slightly smaller than competitors",
      "Occasional CVT hesitation from a stop in cold temperatures — resolves after warm-up",
    ],
    recall_warnings: [],
    maintenance_at_mileage: [
      "Air filter inspection and possible replacement ($25–$40 DIY)",
      "Brake fluid flush may be due depending on age",
      "Confirm tire rotation has been done every 5–7k miles",
    ],
    inspection_checklist: [
      "Test AWD system — feel for hesitation or vibration under mild acceleration",
      "Check all four tires for even tread depth",
      "Test heated seats, Bose audio, and all tech features",
      "Inspect underside for oil leaks or road rash",
      "Open and close power liftgate multiple times",
      "Test blind spot monitoring indicator lights",
    ],
    seller_questions: [
      "Do you have all dealer service records?",
      "Any powertrain warranty remaining? (5yr/60k — may still be active)",
      "Has it been in any accidents or had any paint work?",
      "Why are you selling?",
    ],
    buy_rationale:
      "Excellent buy. 39k miles on a 2020 puts it firmly in the sweet spot — past the first-year depreciation cliff but with plenty of life left, possibly still under powertrain warranty. Zero recalls, zero complaints, AWD, dealer serviced, and priced $1,300 below market. Pull the trigger.",
    price_assessment: "underpriced",
    ownership_cost: {
      annual_maintenance_estimate: 625,
      common_repair_costs: [
        "Brake pads (front): $250–$400",
        "Cabin air filter: $25–$60",
        "Tires (set of 4, all-season): $600–$850",
      ],
      insurance_tier: "low",
      fuel_cost_annual_estimate: 1800,
    },
    negotiation_script:
      "Hi Alicia, thanks for the detailed listing — the CX-5 looks great. I'd like to do a quick pre-purchase inspection at a local shop. If everything checks out, I'd offer $23,800 given that the brake fluid service and tire rotation are likely due. I can pay cash and work around your schedule.",
  },
};

export function getMockAnalysisStream(
  vin: string,
  onChunk: (text: string) => void,
  onResult: (result: AnalysisResult) => void
): void {
  const analysis = MOCK_ANALYSES[vin];
  if (!analysis) {
    const generic: AnalysisResult = {
      listing_id: "demo",
      buy_rating: "CAUTION",
      buy_score: 5,
      reliability_summary:
        "This is a demo listing. In production, Claude generates a full AI analysis based on the vehicle's NHTSA history, mileage, price, and known issues for this make/model/year.",
      known_pain_points: ["Demo mode — connect a backend for real AI analysis"],
      recall_warnings: [],
      maintenance_at_mileage: ["Demo mode — real analysis includes mileage-specific service items"],
      inspection_checklist: ["Demo mode — real analysis includes a detailed inspection checklist"],
      seller_questions: ["Demo mode — real analysis generates targeted seller questions"],
      buy_rationale:
        "This is a demo. The real AI analysis gives a detailed BUY/CAUTION/AVOID recommendation based on all available data.",
      price_assessment: "unknown",
      ownership_cost: {
        annual_maintenance_estimate: null,
        common_repair_costs: [],
        insurance_tier: null,
        fuel_cost_annual_estimate: null,
      },
      negotiation_script:
        "Demo mode — real analysis generates a ready-to-send negotiation message tailored to this specific listing.",
    };
    setTimeout(() => onResult(generic), 800);
    return;
  }

  // Simulate streaming the reliability summary word by word
  const words = analysis.reliability_summary.split(" ");
  let i = 0;
  const interval = setInterval(() => {
    if (i < words.length) {
      onChunk(words[i] + " ");
      i++;
    } else {
      clearInterval(interval);
      onResult(analysis);
    }
  }, 45);
}
